defaultBranch: 'devel'
branchName: 'issue-${issue.number}-${issue.title}'
openDraftPR: true
autoLinkIssue: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
conventionalPrTitles: true
conventionalStyle: semver # Usa prefijos estándar (fix:, feat:)
silent: false