# Generated by roxytest: do not edit by hand!

# File R/steps_and_checks.R: @tests

test_that("Function step() @ L36", {
  data(metaHIV_phy)
  recipe(metaHIV_phy, "RiskGroup2", "Species") |>
      step_metagenomeseq(id = "panallet") |>
      step_metagenomeseq() |> 
      expect_snapshot()
      
  expect_s4_class(
    recipe(metaHIV_phy, "RiskGroup2", "Species") |>
      step_metagenomeseq() |>
      step_metagenomeseq(),
    "Recipe"
  ) |> expect_snapshot()
  
  data(test_prep_rec)
  expect_s4_class(
    test_prep_rec |> 
      bake() |>
      bake(),
   "PrepRecipe"
  ) |> expect_snapshot()
})

