# Generated by roxytest: do not edit by hand!

# File R/deseq2.R: @tests

test_that("[unknown alias] @ L86", {
  data(metaHIV_phy)
  
  test <-
   recipe(metaHIV_phy, "RiskGroup2", "Phylum") |>
   step_subset_taxa(tax_level = "Kingdom", taxa = c("Bacteria", "Archaea")) |>
   step_filter_by_rarity(0.95) |> 
   step_deseq() |> 
   prep()
   
  expect_s4_class(test, "PrepRecipe")
  
  data(test_prep_rec)
  expect_error(step_deseq(test_prep_rec))
})

