# Generated by roxytest: do not edit by hand!

# File R/corncob.R: @tests

test_that("Function step_corncob() @ L84", {
  data(metaHIV_phy)
  
  test <-
   suppressWarnings(recipe(metaHIV_phy, "RiskGroup2", "Phylum")) |>
   step_subset_taxa(tax_level = "Kingdom", taxa = c("Bacteria", "Archaea")) |>
   step_filter_by_abundance() |> 
   step_corncob()
  test <- suppressWarnings(prep(test, parallel = FALSE))
   
  expect_s4_class(test, "PrepRecipe")
  
  data(test_prep_rec)
  expect_error(step_corncob(test_prep_rec))
})

