# Generated by roxytest: do not edit by hand!

# File R/maaslin3.R: @tests

test_that("Function step_maaslin() @ L82", {
  data(metaHIV_phy)
  
  test <-
    suppressWarnings(recipe(metaHIV_phy, "RiskGroup2", "Phylum")) |>
    step_subset_taxa(tax_level = "Kingdom", taxa = c("Bacteria", "Archaea")) |>
    step_filter_by_abundance() |>
    step_maaslin() |>
    step_maaslin(rarefy = TRUE) |>
    step_maaslin(rarefy = "no_seed")
  
  expect_s4_class(suppressWarnings(prep(test, parallel = FALSE)), "PrepRecipe") |>
    expect_snapshot()
  
  data(test_prep_rec)
  expect_error(step_maaslin(test_prep_rec))
})

