# Generated by roxytest: do not edit by hand!

# File R/filter_taxa.R: @tests

test_that("Function step_filter_taxa() @ L39", {
  data(test_prep_rec)
  expect_error(step_filter_taxa(test_prep_rec))
})

