# Generated by roxytest: do not edit by hand!

# File R/linda.R: @tests

test_that("Function step_linda() @ L51", {
  data(metaHIV_phy)
  rec <- recipe(metaHIV_phy) |>
    add_model(~ RiskGroup2, targets = "RiskGroup2", tax_level = "Species")
  expect_equal(length(steps_ids(step_linda(rec))), 1L)
  data(test_prep_rec)
  expect_error(step_linda(test_prep_rec))
})

