# Generated by roxytest: do not edit by hand!

# File R/filter_by_variance.R: @tests

test_that("[unknown alias] @ L41", {
  data(test_prep_rec)
  expect_error(step_filter_by_variance(test_prep_rec))
})

