# Generated by roxytest: do not edit by hand!

# File R/bake.R: @tests

test_that("[unknown alias] @ L91", {
  data(test_rec)
  data(test_prep_rec)
  
  ## Test bake default values
  testthat::expect_error(bake(test_rec))
  testthat::expect_s4_class(bake(test_prep_rec), "PrepRecipe")
  
  ## Test count_cutoff parameter
  testthat::expect_error(cool(bake(test_prep_rec, count_cutoff = 10)))
  
  ## Test exclude parameter
  test <- bake(test_prep_rec, exclude = steps_ids(test_prep_rec, "da")[1])
  cool(test) |> 
    testthat::expect_s3_class("tbl_df") |> 
    testthat::expect_snapshot()
    
  nrow(cool(test)) |>
   testthat::expect_equal(34) |>
   testthat::expect_snapshot()
  
  test <- bake(test_prep_rec, exclude = "force_error")
  testthat::expect_error(cool(test))
  
  ## Test weights parameter
  weights <- c(2, 1, 3)
  names(weights) <- steps_ids(test_prep_rec, "da")
  test <- bake(test_prep_rec, weights = weights)
  cool(test) |> 
    testthat::expect_s3_class("tbl_df") |> 
    testthat::expect_snapshot()
  
  nrow(cool(test)) |> 
    testthat::expect_equal(34) |> 
    testthat::expect_snapshot()
  
  weights <- c(2, 1)
  names(weights) <- steps_ids(test_prep_rec, "da")[1:2]
  test <- bake(test_prep_rec, weights = weights)
  expect_error(cool(test))
})

