# Generated by roxytest: do not edit by hand!

# File R/maaslin2.R: @tests

test_that("[unknown alias] @ L84", {
  data(metaHIV_phy)
  
  test <-
   recipe(metaHIV_phy, "RiskGroup2", "Class") |>
   step_subset_taxa(tax_level = "Kingdom", taxa = c("Bacteria", "Archaea")) |>
   step_filter_by_abundance() |> 
   step_maaslin() |> 
   step_maaslin(rarefy = TRUE) |> 
   step_maaslin(rarefy = "no_seed") 
   
  expect_s4_class(prep(test), "PrepRecipe")
  
  data(test_prep_rec)
  expect_error(step_maaslin(test_prep_rec))
})

