# Generated by roxytest: do not edit by hand!

# File R/"recipe-class.R": @tests

test_that("Function recipe() @ L169", {
  data(metaHIV_phy)
  data(GlobalPatterns, package = "mia")
  
  # 1. Error: Invalid microbiome_object type
  expect_error(
    recipe(data.frame(a = 1:5)),
    class = "dar_error_invalid_microbiome_object"
  )
  
  # 2. Error: Invalid taxonomy rank names (fails with made-up names)
  bad_phy <- metaHIV_phy
  tax_tab <- phyloseq::tax_table(bad_phy)
  colnames(tax_tab) <- paste0("BadRank", seq_len(ncol(tax_tab)))
  phyloseq::tax_table(bad_phy) <- tax_tab
  
  expect_error(
    recipe(bad_phy),
    class = "dar_error_invalid_rank_names"
  )
  
  # 3. Success: Valid taxonomy ranks in UPPERCASE (tests stringr normalization)
  upper_phy <- metaHIV_phy
  tax_tab_up <- phyloseq::tax_table(upper_phy)
  colnames(tax_tab_up) <- toupper(colnames(tax_tab_up))
  phyloseq::tax_table(upper_phy) <- tax_tab_up
  
  expect_s4_class(recipe(upper_phy), "Recipe")
  
  # 4. Error: Invalid var_info missing in metadata
  expect_error(
    suppressWarnings(
      recipe(metaHIV_phy, var_info = "error_var", tax_info = "Species")
    ),
    class = "dar_error_missing_vars"
  )
  
  # 5. Error: Invalid tax_info missing in tax_table
  expect_error(
    suppressWarnings(
      recipe(metaHIV_phy, var_info = "RiskGroup2", tax_info = "error_tax")
    ),
    class = "dar_error_missing_tax"
  )
  
  # 6. Success: Valid TreeSummarizedExperiment
  expect_s4_class(recipe(GlobalPatterns), "Recipe")
  
  # 7. Success: Valid phyloseq
  expect_s4_class(recipe(metaHIV_phy), "Recipe")
})


test_that("Function recipe_validity_problems() @ L323", {
  data(metaHIV_phy)
  
  complete_rec <- suppressWarnings(recipe(
    metaHIV_phy,
    var_info = "RiskGroup2",
    tax_info = "Species"
  ))
  incomplete_rec <- recipe(metaHIV_phy)
  
  expect_true(methods::validObject(complete_rec, test = TRUE))
  expect_true(methods::validObject(incomplete_rec, test = TRUE))
  
  invalid_var <- complete_rec
  invalid_var@var_info <- tibble::tibble(vars = "missing_variable")
  expect_match(
    methods::validObject(invalid_var, test = TRUE),
    "missing_variable"
  )
  
  invalid_tax <- complete_rec
  invalid_tax@tax_info <- tibble::tibble(tax_lev = "Missing_rank")
  expect_match(
    methods::validObject(invalid_tax, test = TRUE),
    "Missing_rank"
  )
  
  malformed_var <- complete_rec
  malformed_var@var_info <- tibble::tibble(wrong = "RiskGroup2")
  expect_match(
    methods::validObject(malformed_var, test = TRUE),
    "var_info"
  )
  
  malformed_tax <- complete_rec
  malformed_tax@tax_info <- tibble::tibble(wrong = "Species")
  expect_match(
    methods::validObject(malformed_tax, test = TRUE),
    "tax_info"
  )
  
  testthat::local_mocked_bindings(
    nsamples = function(x) 0,
    ntaxa = function(x) 0,
    .package = "phyloseq"
  )
  empty_problems <- recipe_validity_problems(complete_rec)
  expect_true(any(grepl("at least one sample", empty_problems)))
  expect_true(any(grepl("at least one taxon", empty_problems)))
})


test_that("Function prep_recipe() @ L566", {
  data(metaHIV_phy)
  rec <- suppressWarnings(recipe(metaHIV_phy, "RiskGroup2", "Species"))
  
  prepped <- prep_recipe(rec, results = list(), bakes = list())
  expect_s4_class(prepped, "PrepRecipe")
  expect_true(methods::validObject(prepped, test = TRUE))
  
  rec@tax_info <- tibble::tibble(tax_lev = "Missing_rank")
  expect_error(
    prep_recipe(rec, results = list(), bakes = list()),
    regexp = "Missing_rank"
  )
})

