# Generated by roxytest: do not edit by hand!

# File R/"recipe-class.R": @tests

test_that("Function recipe() @ L124", {
  data(metaHIV_phy) 
  colnames(metaHIV_phy@tax_table) <-
    c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Sp")
    
  expect_error( 
    recipe(metaHIV_phy, var_info = "RiskGroup2", tax_info = "Species") 
  )
  
  data(GlobalPatterns, package = "mia")
  expect_s4_class(recipe(GlobalPatterns), "Recipe")
})

