# Generated by roxytest: do not edit by hand!

# File R/filter_by_rarity.R: @tests

test_that("Function step_filter_by_rarity() @ L45", {
  data(test_prep_rec)
  expect_error(step_filter_by_rarity(test_prep_rec))
})

