# Generated by roxytest: do not edit by hand!

# File R/ancom.R: @tests

test_that("Function step_ancom() @ L113", {
  data(metaHIV_phy)
  
  test <-
   recipe(metaHIV_phy, "RiskGroup2", "Order") |>
   step_subset_taxa(tax_level = "Kingdom", taxa = c("Bacteria", "Archaea")) |>
   step_filter_by_prevalence() |> 
   step_ancom()
   
  expect_s4_class(prep(test), "PrepRecipe") |> 
    expect_snapshot()
  
  data(test_prep_rec)
  expect_error(step_ancom(test_prep_rec, rarefy = TRUE))
})

