# Generated by roxytest: do not edit by hand!

# File R/rarefaction.R: @tests

test_that("[unknown alias] @ L58", {
  data(metaHIV_phy)
  data(test_prep_rec)
  test <- 
    recipe(metaHIV_phy, var_info = "RiskGroup2", tax_info = "Phylum") |>
    step_rarefaction() 
    
  expect_s4_class(prep(test), "PrepRecipe")
  expect_error(step_rarefaction(test_prep_rec))
})

