# Generated by roxytest: do not edit by hand!

# File R/filter_taxa.R: @tests

test_that("[unknown alias] @ L60", {
  data(metaHIV_phy)
  rec_1 <- 
    recipe(metaHIV_phy, "RiskGroup2", "Species") |>
    step_filter_taxa(.f = "function(x) sum(x > 0) >= (0 * length(x))") |> 
    step_metagenomeseq(rm_zeros = 0)
    
  rec_2 <- 
    recipe(metaHIV_phy, "RiskGroup2", "Species") |>
    step_filter_taxa(.f = "function(x) sum(x > 0) >= (0 * length(x))") |> 
    step_metagenomeseq(rm_zeros = 0.01)
    
  rec_3 <- 
    recipe(metaHIV_phy, "RiskGroup2", "Species") |>
    step_filter_taxa(.f = "function(x) sum(x > 0) >= (0 * length(x))") |> 
    step_metagenomeseq(rm_zeros = NULL)
    
  expect_error(prep(rec_1))
  expect_match(capture_warnings(prep(rec_2)), "NaNs produced", all = TRUE)
  expect_match(capture_warnings(prep(rec_3)), "NaNs produced", all = TRUE)
  expect_s4_class(suppressWarnings(prep(rec_2)), "PrepRecipe")
  expect_s4_class(suppressWarnings(prep(rec_3)), "PrepRecipe")
  
  data(test_prep_rec)
  expect_error(step_filter_taxa(test_prep_rec))
})

