# Generated by roxytest: do not edit by hand!

# File R/recipe_qc.R: @tests

test_that("Function recipe_qc() @ L53", {
  data(test_rec)
  result <- recipe_qc(test_rec)
  expect_named(result, c(
    "group_by", "group", "n", "n_zero", "pct_zero", "pct_all_zero",
    "pct_singletons", "pct_doubletons", "n_samples", "lib_size_min",
    "lib_size_max", "count_mean", "count_max"
  ))
  expect_equal(nrow(result), 1L)
})

