# Generated by roxytest: do not edit by hand!

# File R/filter_by_abundance.R: @tests

test_that("[unknown alias] @ L44", {
  data(test_prep_rec)
  expect_error(step_filter_by_abundance(test_prep_rec))
})

