# Generated by roxytest: do not edit by hand!

# File R/subset_taxa.R: @tests

test_that("Function step_subset_taxa() @ L45", {
  data(test_prep_rec)
  expect_error(step_subset_taxa(test_prep_rec))
})

