# Generated by roxytest: do not edit by hand!

# File R/steps_and_checks.R: @tests

test_that("Function step() @ L31", {
  data(metaHIV_phy)
  expect_s4_class(
    recipe(metaHIV_phy, "RiskGroup2", "Species") |>
      step_metagenomeseq() |>
      step_metagenomeseq(),
    "Recipe"
  )
  
  data(test_prep_rec)
  expect_s4_class(
    test_prep_rec |> 
      bake() |>
      bake(),
   "PrepRecipe"
  )
})

