# Generated by roxytest: do not edit by hand!

# File R/steps_and_checks.R: @tests

test_that("Function step() @ L22", {
  data(metaHIV_phy)
  rec <- recipe(metaHIV_phy) |>
    add_model(~ RiskGroup2, targets = "RiskGroup2", tax_level = "Species") |>
    step_maaslin()
      
  expect_s4_class(rec, "Recipe")
  expect_equal(length(rec@steps), 1)
})


test_that("Function add_step() @ L85", {
  data(metaHIV_phy)
  
  # 1. Test adding steps to a normal Recipe
  rec <- recipe(metaHIV_phy) |>
    add_model(~ RiskGroup2, targets = "RiskGroup2", tax_level = "Species")
  rec <- step_maaslin(rec, id = "test_1")
  expect_equal(length(rec@steps), 1)
  
  # 2. Test duplicate skipping mechanism in Recipe
  # Adding the exact same step should not increase the length
  expect_snapshot({
   rec <- step_maaslin(rec, id = "test_2") 
  })
  expect_equal(length(rec@steps), 1)
  
  # 3. Test adding bakes to a PrepRecipe
  data(test_prep_rec)
  initial_bakes <- length(test_prep_rec@bakes)
  
  # Bake adds a step to the @bakes slot
  prepped <- bake(test_prep_rec)
  expect_equal(length(prepped@bakes), initial_bakes + 1)
  
  # Duplicate bake should be skipped
  expect_snapshot({
     prepped_dup <- bake(prepped)
  })
  expect_equal(length(prepped_dup@bakes), initial_bakes + 1)
})

