# Generated by roxytest: do not edit by hand!

# File R/misc.R: @tests

test_that("Function rand_id() @ L15", {
  set.seed(123); first_id <- rand_id()
  set.seed(123); expect_identical(rand_id(), first_id)
  expect_match(first_id, "^step__"); expect_true(sub("^step__", "", first_id) %in% pastry_df$id)
})


test_that("Function get_comparisons() @ L49", {
  data("metaHIV_phy")
  phy <- metaHIV_phy
  var <- "RiskGroup2"
  
  is_list <- get_comparisons(var, phy)
  is_tibb <- get_comparisons(var, phy, as_list = FALSE)
  filtered <- get_comparisons(var, phy, n_cut = 30)
  
  expect_equal(class(is_list), "list")
  expect_s3_class(is_tibb, "tbl_df")
  expect_length(is_list, 3)
  expect_equal(nrow(is_tibb), 3)
  expect_length(filtered, 1)
})


test_that("Function to_tibble() @ L100", {
  data("metaHIV_phy")
  phy <- metaHIV_phy
  df <- phyloseq::otu_table(phy)
  
  test_1 <- to_tibble(df)
  test_2 <- to_tibble(df, id_name = "random_id")
  
  expect_length(test_1, 157)
  expect_s3_class(test_1, "tbl_df")
  expect_s3_class(test_2, "tbl_df")
  expect_equal(names(test_1)[1], "otu_id")
  expect_equal(names(test_2)[1], "random_id")
})


test_that("Function step_to_call() @ L162", {
  # 1. Test standard string and numeric parameters
  step_standard <- step("maaslin",
    id = "maaslin__123",
    transform = "LOG",
    min_abundance = 0.1
  )
  call_standard <- step_to_call(step_standard)
  
  expect_true(is.call(call_standard))
  expect_true(is.function(call_standard[[1]]))
  expect_equal(call_standard[[1]], run_maaslin)
  expect_equal(rlang::call_args(call_standard)$transform, "LOG")
  expect_equal(rlang::call_args(call_standard)$min_abundance, 0.1)
  
  # 2. Test with a function parameter (The main reason for this refactor)
  my_fun <- function(x) sum(x > 0) >= (0.03 * length(x))
  step_func <- step("filter_taxa",
    id = "filter_taxa__abc",
    .f = my_fun
  )
  call_func <- step_to_call(step_func)
  
  expect_true(is.call(call_func))
  expect_true(is.function(call_func[[1]]))
  expect_equal(call_func[[1]], run_filter_taxa)
  expect_true(is.function(rlang::call_args(call_func)$.f))
  
  # 3. Test with a formula parameter
  step_formula <- step("deseq",
    id = "deseq__xyz",
    design = ~ RiskGroup2
  )
  call_formula <- step_to_call(step_formula)
  
  expect_true(is.call(call_formula))
  expect_true(is.function(call_formula[[1]]))
  expect_equal(call_formula[[1]], run_deseq)
  expect_true(inherits(rlang::call_args(call_formula)$design, "formula"))
})


test_that("Function find_intersections() @ L225", {
  data(test_prep_rec)
  res_1 <- find_intersections(
    test_prep_rec, steps = steps_ids(test_prep_rec, type = "da")
  )
  res_2 <- find_intersections(
    test_prep_rec, steps = steps_ids(test_prep_rec, type = "da")[-1]
  )
  res_3 <- find_intersections(
    test_prep_rec, steps = steps_ids(test_prep_rec, type = "da")[-2]
  )
  
  expect_equal(nrow(res_1), 52)
  expect_equal(nrow(res_2), 27)
  expect_equal(nrow(res_3), 41)
  expect_s3_class(res_1, "tbl_df")
})


test_that("Function steps_ids() @ L310", {
  data(test_prep_rec)
  print(test_prep_rec) |> expect_snapshot()
  rec <- test_prep_rec
  expect_equal(
    steps_ids(rec),
    c("subset_taxa__Viennoiserie",
      "filter_taxa__Karakudamono",
      "maaslin__Welsh_cake",
      "deseq__Coussin_de_Lyon"
     )
  )
  expect_equal(
    steps_ids(rec, "da"),
    c("maaslin__Welsh_cake", "deseq__Coussin_de_Lyon")
  )
  expect_equal(
    steps_ids(rec, "prepro"),
    c("subset_taxa__Viennoiserie", "filter_taxa__Karakudamono")
  )
  expect_error(steps_ids(rec, "das"))
  expect_type(steps_ids(rec), "character")
})

