# Generated by roxytest: do not edit by hand!

# File R/"recipe-class.R": @tests

test_that("Function recipe() @ L126", {
  data(metaHIV_phy) 
    
  expect_error( 
    recipe(metaHIV_phy, var_info = "error_var", tax_info = "Species") 
  )
  
  expect_error( 
    recipe(metaHIV_phy, var_info = "RiskGroup2", tax_info = "error_tax") 
  )
  
  data(GlobalPatterns, package = "mia")
  expect_s4_class(recipe(GlobalPatterns), "Recipe")
})

