# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <Recipe-class>
  # <ancom_stats_tbl>
  # <run_bake>
  # <run_deseq>
  # <prepro_lefse>
  # <step_to_expr>
  # <find_intersections>
  # <import_steps>
  # <.zero_prepro>
  # <recipes_pkg_check>
  # <corr_heatmap>
  # <mutual_plt>
  # <.abundance_boxplot>
  # <.abundance_heatmap>
  # <intersection_df>
  # <cool>
  # <run_subset_taxa>
  # <run_wilcox>
  ".",
  # <run_lefse>
  "adjp",
  # <run_maaslin>
  "coef",
  # <mutual_plt>
  "comparison",
  # <.count_summary>
  "count_max",
  # <.count_summary>
  "count_mean",
  # <run_aldex>
  # <mutual_plt>
  "effect",
  # <mutual_plt>
  "effect_v",
  # <run_wilcox>
  "estimate",
  # <run_maaslin>
  "feature",
  # <run_lefse>
  "features",
  # <prepro_lefse>
  "Kingdom",
  # <ancom_stats_tbl>
  "lfc",
  # <.count_summary>
  "lib_size",
  # <run_deseq>
  "log2FoldChange",
  # <run_bake>
  # <exclusion_plt>
  # <mutual_plt>
  "method",
  # <run_bake>
  # <mutual_plt>
  # <.abundance_boxplot>
  # <.abundance_heatmap>
  "method_count",
  # <.zero_stats>
  "n_zero",
  # <find_intersections>
  "name",
  # <.zero_groups>
  "no_zero",
  # <run_lefse>
  "otu",
  # <rm_zero_variance>
  "otu_id",
  # <corncob_stats_tbl>
  # <run_deseq>
  # <run_wilcox>
  "padj",
  # <run_bake>
  "ponderation",
  # <run_maaslin>
  "pval_individual",
  # <run_lefse>
  # <kruskal_test>
  "pvalue",
  # <run_maaslin>
  "qval",
  # <run_maaslin>
  "qval_individual",
  # <prepro_lefse>
  "RTC",
  # <.count_summary>
  # <.abundance_heatmap>
  # <sample_data>
  # <run_wilcox>
  "sample_id",
  # <run_lefse>
  "scores",
  # <Recipe-class>
  # <find_intersections>
  "sum_methods",
  # <Recipe-class>
  "tax_lev",
  # <run_bake>
  # <corncob_stats_tbl>
  # <mutual_plt>
  # <.abundance_boxplot>
  # <.abundance_heatmap>
  "taxa",
  # <run_bake>
  # <corncob_stats_tbl>
  # <run_lefse>
  # <run_maaslin>
  # <find_intersections>
  # <.zero_groups>
  # <mutual_plt>
  # <.abundance_boxplot>
  # <.abundance_heatmap>
  # <.otu_method_count>
  # <tax_table>
  # <intersection_df>
  # <run_wilcox>
  "taxa_id",
  # <ancom_stats_tbl>
  "taxon",
  # <exclusion_plt>
  "total",
  # <rm_zero_variance>
  # <kruskal_test>
  # <find_intersections>
  # <.zero_stats>
  # <.zero_groups>
  # <.count_summary>
  # <.abundance_boxplot>
  # <.abundance_heatmap>
  # <.otu_method_count>
  "value",
  # <run_aldex>
  "we.eBH",
  NULL
))
